<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diff_bot">

    <!--................................ XACRO CONSTANTS .............................. -->

    <!-- MEASUREMENTS (METRIC UNITS)-->
    
    <xacro:property name="base_link_mass" value="20"/>
    <xacro:property name="base_link_length" value="1.0006"/>
    <xacro:property name="base_link_width" value="0.660"/>
    <xacro:property name="base_link_height" value="0.235"/>

    <xacro:property name="ground_clearance" value="0.0335"/>
    <xacro:property name="wheel_separation" value="0.4445"/>

    <xacro:property name="lidar_height" value="0.6731"/>
    <xacro:property name="aluminium_extrusion_width" value="0.02"/>

    <xacro:property name="main_wheel_mass" value="1"/>
    <xacro:property name="main_wheel_max_torque" value="20000"/>
    <xacro:property name="main_wheel_wheel_friction" value="5.0"/>
    <xacro:property name="main_wheel_radius" value="0.1015"/>
    <xacro:property name="main_wheel_width" value="0.05"/>


    <xacro:property name="castor_wheel_mass" value="0.1"/>
    <xacro:property name="castor_wheel_friction" value="0.0"/>
    <xacro:property name="castor_wheel_radius" value="0.03"/>
    <!-- Castor wheel gap is the gap it has from the edges of the main body box -->
    <xacro:property name="castor_wheel_gap" value="0.03"/>    
    <!-- a small constant -->
    <xacro:property name="eps" value="0.003"/>

    

    <xacro:property name="two_d_lidar_update_rate" value="30"/>
    <xacro:property name="two_d_lidar_sample_size" value="361"/>
    <xacro:property name="two_d_lidar_min_angle" value="0"/>
    <xacro:property name="two_d_lidar_max_angle" value="360"/>
    <xacro:property name="two_d_lidar_min_range" value="0.55"/>
    <xacro:property name="two_d_lidar_max_range" value="16"/>


    <xacro:arg name="use_ros2_control" default="false" />
    
    <xacro:arg name="robot_namespace" default=""/>
    <xacro:arg name="wheel_odom_topic" default="odom" />
    <xacro:arg name="two_d_lidar_enabled" default="true" />
    <xacro:arg name="publish_wheel_odom_tf" default="true" />
    <xacro:arg name="ground_truth_frame" default="map"/>
    <xacro:arg name="odometry_source" default="world" />

    <xacro:property name="odometry_source" value="$(arg odometry_source)"/>

    <!-- ............................... LOAD MACROS ................................. -->

    <xacro:include filename="$(find diff_bot)/urdf/macros.urdf.xacro"/>
    <xacro:include filename="$(find diff_bot)/urdf/gazebo_plugins.urdf.xacro"/>

    <xacro:if value="$(arg use_ros2_control)">
        <xacro:include filename="$(find diff_bot)/urdf/ros2_control.xacro"/>
    </xacro:if>


    <!-- ................................ BASE LINK .................................. -->
    <link name="base_footprint"/>


    <link name="base_link">
    
    	<inertial>
            <mass value="${base_link_mass}" />
            <xacro:box_inertia m="${base_link_mass}" x="${base_link_length}" y="${base_link_width}" z = "${base_link_height}"/>
        </inertial>

        <collision>
            <origin xyz="0 0 ${base_link_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${base_link_length} ${base_link_width} ${base_link_height}"/>
            </geometry>
        </collision>

        
        <!-- Main chassis box visual -->
        <visual>
            <origin xyz="0 0 ${base_link_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${base_link_length} ${base_link_width} ${base_link_height}"/>
            </geometry>
        </visual>


        <!-- Lidar extrusion rod visual -->
        <visual>
            <origin xyz="${base_link_length/2 - aluminium_extrusion_width/2} 0 ${lidar_height/2 + base_link_height}" rpy="0 0 0" />
            <geometry>
                <box size="${aluminium_extrusion_width} ${aluminium_extrusion_width} ${lidar_height}"/>
            </geometry>
        </visual>


        <!-- Lidar base visual -->
        <visual>
            <origin xyz="${base_link_length/2 - aluminium_extrusion_width/2} 0 ${lidar_height + base_link_height - 0.035}" rpy="0 0 0" />
            <geometry>
                <box size="0.1 0.1 0.01"/>
            </geometry>
        </visual>

    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0 ${ground_clearance}" rpy="0 0 0.0" />
    </joint>

    <gazebo reference="base_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    
    
    <!-- ................................ MAIN WHEELS ..................................... -->
    
    
    <xacro:main_wheel dexterity="left" origin_x="0" origin_y="${wheel_separation/2}" origin_z="${main_wheel_radius-ground_clearance}"/>
    <xacro:main_wheel dexterity="right" origin_x="0" origin_y="-${wheel_separation/2}" origin_z="${main_wheel_radius-ground_clearance}"/>


    <!-- ................................ CASTOR WHEELS ..................................... -->

    <xacro:castor_wheel cardinality="front" dexterity="left" origin_x="${base_link_length/2 - castor_wheel_gap}" origin_y="${base_link_width/2 - castor_wheel_gap}" origin_z="${castor_wheel_radius-ground_clearance+eps}"/>
    <xacro:castor_wheel cardinality="front" dexterity="right" origin_x="${base_link_length/2 - castor_wheel_gap}" origin_y="-${base_link_width/2 - castor_wheel_gap}" origin_z="${castor_wheel_radius-ground_clearance+eps}"/>

    <xacro:castor_wheel cardinality="back" dexterity="left" origin_x="-${base_link_length/2 - castor_wheel_gap}" origin_y="${base_link_width/2 - castor_wheel_gap}" origin_z="${castor_wheel_radius-ground_clearance+eps}"/>
    <xacro:castor_wheel cardinality="back" dexterity="right" origin_x="-${base_link_length/2 - castor_wheel_gap}" origin_y="-${base_link_width/2 - castor_wheel_gap}" origin_z="${castor_wheel_radius-ground_clearance+eps}"/>

    <!-- ............................. 2D LIDAR ........................................ -->

    <link name="two_d_lidar">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="0.06" radius="0.075"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="0.06" radius="0.075"/>
            </geometry>
        </visual>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.1"/>
            <xacro:cylinder_inertia m="0.1" r="0.075" h="0.06"/>
        </inertial>
    </link>

    <joint name="two_d_lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="two_d_lidar"/>
        <origin xyz="${base_link_length/2 - aluminium_extrusion_width/2} 0 ${lidar_height + base_link_height}" rpy="0 0 0" />
    </joint>

    <gazebo reference="two_d_lidar">
        <material>Gazebo/Black</material>
    </gazebo>


    <!-- ............................. IMU ........................................ -->

    <link name="imu_frame"/>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_frame"/>
        <origin xyz="0.0 0.0 0.08" rpy="0.0 0.0 0.0"/>
    </joint>


</robot>
