<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diff_bot">

    <gazebo>
        <static>false</static>
    </gazebo>


    <xacro:if value="$(arg use_ros2_control)">
        <gazebo>
            <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
                <parameters>/home/akarsh22/bot_ws/src/diff_bot/config/diff_controller.yaml</parameters>
            </plugin>
        </gazebo>
    </xacro:if>

    <!-- .....................DIFFERENTIAL DRIVE PLUGIN................................... -->

    <xacro:unless value="$(arg use_ros2_control)">
        <gazebo>
            <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
                <ros>
                    <namespace>$(arg robot_namespace)</namespace>
                    <remapping>cmd_vel:=cmd_vel</remapping>
                    <remapping>odom:=odom</remapping>
                </ros>
                <legacy_mode>false</legacy_mode>
                <update_rate>20.0</update_rate>
                <left_joint>left_wheel_joint</left_joint>
                <right_joint>right_wheel_joint</right_joint>
                <wheel_separation>${wheel_separation + main_wheel_width}</wheel_separation>
                <wheel_diameter>${main_wheel_radius*2}</wheel_diameter>
                <robot_base_frame>base_footprint</robot_base_frame>
                <max_wheel_torque>${main_wheel_max_torque}</max_wheel_torque>
                <command_topic>cmd_vel</command_topic>
                <odometry_topic>$(arg wheel_odom_topic)</odometry_topic>
                <odometry_frame>odom</odometry_frame>
                <publish_odom_tf>true</publish_odom_tf>
                <publish_wheel_tf>false</publish_wheel_tf>
                <publish_odom>false</publish_odom>
                <max_wheel_acceleration>5.0</max_wheel_acceleration>
                <odometry_source>1</odometry_source>
            </plugin>
        </gazebo>

        <gazebo>
            <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
                <robot_namespace>/</robot_namespace>
                <joint_name>left_wheel_joint</joint_name>
                <joint_name>right_wheel_joint</joint_name>
                <update_rate>30</update_rate>
            </plugin>
        </gazebo>
    </xacro:unless>

    

    <!-- ........................... 2D LIDAR PLUGIN ................................... -->


    <gazebo reference="two_d_lidar">
        <gravity>true</gravity>
        <sensor type="gpu_ray" name="two_d_lidar">
            <pose>0 0 0 0 0 0</pose>
            <visualize>false</visualize>
            <update_rate>${two_d_lidar_update_rate}</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>${two_d_lidar_sample_size}</samples>
                        <resolution>1</resolution>
                        <min_angle>${radians(two_d_lidar_min_angle)}</min_angle>
                        <max_angle>${radians(two_d_lidar_max_angle)}</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>${two_d_lidar_min_range}</min>
                    <max>${two_d_lidar_max_range}</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.0</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_ros_laser" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <remapping>~/out:=$(arg robot_namespace)/scan</remapping>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>two_d_lidar</frame_name>
            </plugin>
        </sensor>
    </gazebo>


    <!--............................... IMU PLUGIN (REMOVE THIS SECTION IF IMU IS NOT REQUIRED) ..................................... -->

    <gazebo reference="imu_frame">
        <sensor name="imu" type="imu">
            <always_on>true</always_on>
            <update_rate>30</update_rate>
            <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
                <ros>
                    <namespace>$(arg robot_namespace)</namespace>
                    <remapping>~/out:=imu/data_raw</remapping>
                </ros>
            </plugin>
        </sensor>
    </gazebo>
    
</robot>